PACKAGE_NAME="trustix-datapath-helpers"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="trustix_datapath_helpers"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="no"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make clean KDIR=${kernel_source_dir}"
