#!/usr/bin/env bash
if [ -z "${BASH_VERSION:-}" ]; then
  echo "ERROR: scripts/update-embedded-bpf.sh requires GNU bash 4+" >&2
  exit 2
fi
set -Eeuo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
asset_dir="${repo_root}/internal/dataplane/ebpf/bpf"
manifest_path="${asset_dir}/embedded_bpf_manifest.txt"
builder="${repo_root}/scripts/build-embedded-bpf.sh"
mode="update"
clang_bin="${CLANG:-}"

usage() {
  cat <<'EOF'
usage: scripts/update-embedded-bpf.sh [--clang CLANG]
       scripts/update-embedded-bpf.sh --check

Rebuilds the tracked embedded eBPF objects and writes their freshness manifest.
--check verifies the manifest against the current sources and tracked objects.
EOF
}

log() {
  printf '[trustix-bpf] %s\n' "$*" >&2
}

die() {
  log "ERROR: $*"
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

sha256_file() {
  sha256sum "$1" | cut -d ' ' -f 1
}

write_manifest() {
  local out="$1"
  local object source flags source_path object_path
  {
    printf '# TrustIX embedded eBPF manifest v1\n'
    printf '# Generated by scripts/update-embedded-bpf.sh. Do not edit by hand.\n'
    printf '# object|source|clang_flags|source_sha256|object_sha256\n'
    while IFS='|' read -r object source flags; do
      [[ -n "$object" ]] || continue
      source_path="${repo_root}/${source}"
      object_path="${asset_dir}/${object}"
      [[ -f "$source_path" ]] || die "missing eBPF source: ${source}"
      [[ -f "$object_path" ]] || die "missing embedded eBPF object: ${object}"
      printf '%s|%s|%s|%s|%s\n' \
        "$object" \
        "$source" \
        "$flags" \
        "$(sha256_file "$source_path")" \
        "$(sha256_file "$object_path")"
    done < <("${BASH:-bash}" "$builder" --print-specs)
  } >"$out"
}

check_manifest() {
  local tmp
  tmp="$(mktemp "${TMPDIR:-/tmp}/trustix-bpf-manifest.XXXXXX")"
  trap 'rm -f "$tmp"' RETURN
  write_manifest "$tmp"
  if [[ ! -f "$manifest_path" ]]; then
    log "embedded eBPF manifest is missing: ${manifest_path}"
    log "run: bash scripts/update-embedded-bpf.sh"
    return 1
  fi
  if ! cmp -s "$manifest_path" "$tmp"; then
    log "embedded eBPF manifest is stale"
    if command -v diff >/dev/null 2>&1; then
      diff -u "$manifest_path" "$tmp" || true
    fi
    log "run: bash scripts/update-embedded-bpf.sh"
    return 1
  fi
  log "embedded eBPF manifest is current"
}

update_objects() {
  local tmp object source flags built
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/trustix-bpf.XXXXXX")"
  trap 'rm -rf "$tmp"' RETURN
  if [[ -n "$clang_bin" ]]; then
    "${BASH:-bash}" "$builder" --out "$tmp" --clang "$clang_bin"
  else
    "${BASH:-bash}" "$builder" --out "$tmp"
  fi
  mkdir -p "$asset_dir"
  while IFS='|' read -r object source flags; do
    [[ -n "$object" ]] || continue
    built="${tmp}/${object}"
    [[ -f "$built" ]] || die "builder did not produce ${object}"
    cp "$built" "${asset_dir}/${object}"
  done < <("${BASH:-bash}" "$builder" --print-specs)
  write_manifest "$manifest_path"
  log "updated embedded eBPF objects and manifest"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"; shift ;;
    --clang)
      [[ $# -ge 2 ]] || die "--clang requires a value"
      clang_bin="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      die "unknown argument: $1" ;;
  esac
done

need_cmd sha256sum
case "$mode" in
  check) check_manifest ;;
  update) update_objects ;;
  *) die "unknown mode: ${mode}" ;;
esac
